name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # First: Run unit tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Run linter
      run: yarn lint
      
    - name: Run TypeScript check
      continue-on-error: true
      run: npx tsc --noEmit
      
    - name: Run unit tests (if available)
      run: |
        # Skip running tests here since we have Playwright tests that run in a separate job
        echo "Skipping unit tests - Playwright tests will run in the next job"

  # Second: Run Playwright tests after unit tests pass
  # Note: Tests run against local build since Vercel preview deployments may have authentication
  playwright-tests:
    name: Playwright E2E Tests
    needs: unit-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: success()
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install
      
    - name: Build application
      run: yarn build
      
    - name: Start application in background
      run: |
        yarn start &
        echo "Waiting for Next.js to start..."
        # Give the app time to start
        sleep 10
        # Check if the app is running
        curl -f http://localhost:3000 || (echo "App failed to start" && exit 1)
        echo "Application is ready!"
      
    - name: Get Playwright version
      id: playwright-version
      run: |
        echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV
        
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn playwright:install
      
    - name: Run Playwright tests
      run: yarn test
      env:
        BASE_URL: http://localhost:3000
      
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30